language: node_js
node_js:
  - 13
services:
  - docker
script:
  - docker build -t udagram-api-feed ./udagram-api/feed-api
  - docker build -t udagram-api-user ./udagram-api/user-api
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-api-feed sontx/udagram-api-feed:v2
  - docker tag udagram-api-user sontx/udagram-api-user:v2
  - docker tag reverseproxy sontx/reverseproxy:v2
  - docker tag udagram-frontend sontx/udagram-frontend:v2
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push sontx/udagram-api-feed:v2
  - docker push sontx/udagram-api-user:v2
  - docker push sontx/reverseproxy:v2
  - docker push sontx/udagram-frontend:v2